# Generated by Django 5.2.3 on 2025-07-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('imagen', models.ImageField(upload_to='slider_images/')),
                ('prioridad', models.PositiveIntegerField(verbose_name='Prioridad')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
