# Generated by Django 5.2.3 on 2025-07-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='prioridad',
        ),
    ]
