# Generated by Django 5.2.3 on 2025-07-27 14:12

import django.db.models.deletion
import operaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, default='operaciones/anuncios/anuncio.jpg', null=True, upload_to=operaciones.models.get_image_filename)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('accion', models.CharField(choices=[('publicado', 'Publicado'), ('borrador', 'Borrador')], default='borrador', max_length=10)),
                ('anuncio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subanuncios', to='operaciones.anuncio', verbose_name='Anuncio')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
