# Generated by Django 5.2.3 on 2025-07-20 14:02

import django.db.models.deletion
import operaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncios',
            name='usuario',
        ),
        migrations.AddField(
            model_name='anuncios',
            name='anuncio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.anuncios', verbose_name='Anuncios'),
        ),
        migrations.AddField(
            model_name='anuncios',
            name='imagen',
            field=models.ImageField(blank=True, default='operaciones/anuncios/anuncio.jpg', null=True, upload_to=operaciones.models.get_image_filename),
        ),
    ]
