# Generated by Django 5.2.3 on 2025-07-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_remove_anuncios_usuario_anuncios_anuncio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='anuncio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.anuncios', verbose_name='Anuncio'),
        ),
    ]
