# Generated by Django 5.2.3 on 2025-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_anuncio_delete_anuncios'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='accion',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('borrador', 'Borrador')], default='borrador', max_length=10),
        ),
    ]
