# Generated by Django 5.2.3 on 2025-06-30 22:57

import comunidad.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=45, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=45, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(max_length=45, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('imagen', models.ImageField(blank=True, default='comunidad/default-user.jpeg', null=True, upload_to=comunidad.models.get_image_filename, verbose_name='Imagen de Perfil')),
                ('correo', models.EmailField(max_length=50, unique=True, verbose_name='Correo')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('CE', 'Cédula de Extranjería')], max_length=2, verbose_name='Tipo de Documento')),
                ('documento', models.PositiveIntegerField(unique=True, verbose_name='Documento')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('EMP', 'Empleado'), ('RH', 'Recursos Humanos')], default='EMP', max_length=5, verbose_name='Rol')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('departamento', models.CharField(blank=True, help_text='Departamento al que pertenece el usuario', max_length=100, null=True, verbose_name='Departamento')),
                ('cargo', models.CharField(blank=True, help_text='Cargo o posición del usuario', max_length=100, null=True, verbose_name='Cargo')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Django')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['primer_apellido', 'primer_nombre'],
                'permissions': [('can_manage_all_users', 'Puede gestionar todos los usuarios'), ('can_view_reports', 'Puede ver reportes'), ('can_manage_empleados', 'Puede gestionar empleados')],
            },
        ),
    ]
