# Generated by Django 5.2.3 on 2025-07-30 02:02

import comunidad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='comunidad\\default-user.jpeg', null=True, upload_to=comunidad.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula'), ('CE', 'Cédula de Extrangería')], max_length=2, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
