# Generated by Django 5.2.3 on 2025-08-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_alter_usuario_options_remove_usuario_creado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField(unique=True)),
                ('salario_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
