# Generated by Django 5.2.3 on 2025-08-01 01:44

import comunidad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_configuraciongeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='comunidad/default-user.jpeg', null=True, upload_to=comunidad.models.get_image_filename),
        ),
    ]
