# Generated by Django 5.2.3 on 2025-07-14 14:46

import comunidad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_alter_usuario_correo_alter_usuario_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='comunidad/default-user.jpeg', null=True, upload_to=comunidad.models.get_image_filename),
        ),
    ]
