# Generated by Django 5.2.3 on 2025-07-14 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0006_registrohoras_delete_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohoras',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.usuario', verbose_name='Administrador'),
        ),
    ]
