# Generated by Django 5.2.3 on 2025-08-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0006_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoras',
            name='pago_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
