# Generated by Django 5.2.3 on 2025-08-07 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0007_registrohoras_pago_total_registrohoras_valor_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohoras',
            name='valor_hora',
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='horas_extras_diurnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='horas_extras_nocturnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='horas_normales_diurnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='horas_normales_nocturnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='recargo_dominical',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='recargo_festivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='recargo_nocturno',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.usuario'),
        ),
    ]
