# Generated by Django 5.2.3 on 2025-07-14 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0008_alter_registrohoras_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohoras',
            name='permisos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.usuario'),
        ),
    ]
