# Generated by Django 5.2.3 on 2025-08-07 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0009_alter_registrohoras_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohoras',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='horas_extras_diurnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='horas_extras_nocturnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='horas_normales_diurnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='horas_normales_nocturnas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='recargo_dominical',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='recargo_festivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registrohoras',
            name='recargo_nocturno',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
