# Generated by Django 5.2.3 on 2025-08-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0010_alter_registrohoras_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohoras',
            name='pago_total',
        ),
    ]
