# Generated by Django 5.2.3 on 2025-07-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0010_anuncios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohoras',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.usuario', verbose_name='Administrador'),
        ),
        migrations.DeleteModel(
            name='Anuncios',
        ),
    ]
