# Generated by Django 5.2.3 on 2025-07-25 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0012_alter_usuario_user_registrohorario_solicitudpermiso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='user',
        ),
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('permisos', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.usuario', verbose_name='Administrador')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroHorario',
        ),
        migrations.DeleteModel(
            name='SolicitudPermiso',
        ),
    ]
