# Generated by Django 5.2.3 on 2025-07-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0013_remove_solicitudpermiso_user_registrohoras_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroHoras',
        ),
    ]
