# Generated by Django 5.2.3 on 2025-07-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0016_registrohorario_documento_identidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrohorario',
            old_name='horas_extras',
            new_name='horas_extras_diurnas',
        ),
        migrations.AddField(
            model_name='registrohorario',
            name='horas_extras_nocturnas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='registrohorario',
            name='horas_normales_diurnas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='registrohorario',
            name='horas_normales_nocturnas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='registrohorario',
            name='recargo_dominical',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='registrohorario',
            name='recargo_festivo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='registrohorario',
            name='recargo_nocturno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
