# Generated by Django 5.2.3 on 2025-07-26 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0017_rename_horas_extras_registrohorario_horas_extras_diurnas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohorario',
            name='documento_identidad',
        ),
        migrations.AlterField(
            model_name='registrohorario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
